import { Metadata } from "next";

export const metadata: Metadata = {
    title: "Admin Page" + " | " + process.env.NODE_ENV,
    description: "Generated by create next app",
};


export default async function Page({ params: { lang } } : { params: { lang: string } }) {
    return (
        <main className="flex min-h-screen flex-col items-center justify-between p-24">
        <h1>Admin Page</h1>
            <p className="text-xs">Lang: {lang}</p>
            <p>see all art projects</p>
            <p>see all artists</p>
            <p>see all users</p>
            <p>dashboard?</p>
        </main>
    )
}