import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export async function generateStaticParams() {
  return [{ lang: 'en-US' }, { lang: 'fr' }]
}

export default function RootLayout({
  children, params
}: Readonly<{
  children: React.ReactNode;
  params: { lang: string };
}>) {
  return (
    <html lang={params.lang || "en-US"} data-theme="forest">
      <body className={inter.className}>
        <pre className="max-w-80 overflow-scroll">{JSON.stringify(params, null, 2)}</pre>
        <p>{params.lang ?? "no params.lang!"}</p>
        {children}
      </body>
    </html>
  );
}
