import type { Metadata } from "next";
import { Inter, Raleway } from "next/font/google";
import "@/app/globals.css";
import { i18n, type Locale } from "@/i18n-config";
import Nav from "../_components/nav";
import { Providers } from "./providers";

const inter = Inter({ subsets: ["latin"] });
const displayFont = Raleway({ weight: ['400', '700'], subsets: ["latin"] });

export const metadata: Metadata = {
    title: "Lang Layout" + " | " + process.env.NODE_ENV,
    description: "Generated by create next app",
    icons: {
        icon: '/favicon.ico', // /public path
    },
};

export async function generateStaticParams() {
    // Generate static pages for each language
    return i18n.locales.map((locale) => ({ lang: locale }));
}

export default function RootLayout({
    children, params
}: Readonly<{
    children: React.ReactNode;
    params: { lang: Locale };
}>) {
    return (
        <html lang={params.lang || "en-US"}>
            <Providers>
                <head>
                <link rel="icon" href="/favicon.ico" sizes="any" />
                </head>
                
                <body className={`${displayFont.className} flex flex-col min-h-screen`}>
                    <Nav lang={params.lang} />
                    <div className="h-[--height-navbar]"></div>
                    {children}
                </body>
            </Providers>
        </html>
    );
}
    