import type { Metadata } from "next";
import { Inter, Raleway } from "next/font/google";
import "@/app/globals.css";
import { i18n, type Locale } from "@/i18n-config";

const inter = Inter({ subsets: ["latin"] });
const displayFont = Raleway({ weight: ['400', '700'], subsets: ["latin"] });

export const metadata: Metadata = {
    title: "Lang Layout",
    description: "Generated by create next app",
};

export async function generateStaticParams() {
    // Generate static pages for each language
    return i18n.locales.map((locale) => ({ lang: locale }));
}

export default function RootLayout({
    children, params
}: Readonly<{
    children: React.ReactNode;
    params: { lang: Locale };
}>) {
    return (
        <html lang={params.lang || "en-US"}>
            <body className={displayFont.className}>
                {children}
            </body>
        </html>
    );
}
    