import type { Metadata } from "next";
import { Inter, Raleway } from "next/font/google";
import "@/app/globals.css";

const inter = Inter({ subsets: ["latin"] });
const displayFont = Raleway({ weight: ['400', '700'], subsets: ["latin"] });

export const metadata: Metadata = {
    title: "Lang Layout",
    description: "Generated by create next app",
};

export async function generateStaticParams() {
    // Generate static pages for each language
    return [{ lang: 'en-US' }, { lang: 'fr' }]
}

export default function LangLayout({
    children, params
}: Readonly<{
    children: React.ReactNode;
    params: { lang: string };
}>) {
    return (
        <html lang={params.lang || "en-US"}>
            <body className={displayFont.className}>
                {children}
            </body>
        </html>
    );
}
    