import { type Locale } from "@/i18n-config"
import { Metadata } from "next";
import { User } from "@/app/_components/user";
import prisma from "@/prisma"


export const metadata: Metadata = {
    title: "Lang Page" + " | " + process.env.NODE_ENV,
    description: "Generated by create next app",
};


export default async function Page({ params: { lang } } : { params: { lang: Locale } }) {
    const prismaUser = await prisma.user.findUnique({where: {id: "0f86eabc-42e1-4687-b6b1-42654fcf036b"}})
    console.log('USER:', prismaUser)
    return (
        <main className="flex flex-col items-center justify-between p-24">
        <h1>Page in Lang</h1>
        <p>Lang: {lang}</p>
        <h1>Connected ??</h1>
        <User />
        <br />
        <h1>Prisma users?? User id 0f86eabc-42e1-4687-b6b1-42654fcf036b ??</h1>
        {
            prismaUser && (
                <div>
                    <p>id: {prismaUser.id}</p>
                    <p>name: {prismaUser.name}</p>
                    <p>email: {prismaUser.email}</p>
                    <p>role: {prismaUser.role}</p>
                </div>
            )
        }
        {/* <p>{prismaUser?.name || prismaUser?.email}</p> */}
        </main>
    )
}